/* substrate:cn — generated by the Substrate install (SUB-169); re-written on every install */
import { createCn } from "cn/config"

/* The design system's own utilities, told to the class merger: without this, cn("text-small text-destructive")
 * reads two colours and drops the size, and cn("p-inset-md", className) cannot override the padding. */
export const cn = createCn({ extend: { theme: { text: ["display","h1","h2","h3","lead","body","small","caption","micro"], radius: ["sm","md","lg","xl","2xl","controls","containers","inline","chip","track"], shadow: ["xs","sm","md","lg","xl"], spacing: ["hairline","optical","inset-2xs","inset-xs","inset-sm","inset-md","inset-lg","inset-xl","stack-xs","stack-sm","stack-md","stack-lg","region","section","section-lg","chapter","chapter-lg","control-2xs","control-xs","control-sm","control-md","control-lg","control-xl","frame-pad","frame-gutter","frame-2xl","frame-xl","frame-lg","frame-md","frame-sm","frame-xs"] } } })
